### PR TITLE
Add method willExperIn

### PR DESCRIPTION
**Pull request by DemianD**
Issue #2 

Also added the moded isExpired() to the readme.md file.
Didn't know if it was necessary.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thanks for contributing.

Let's make it a bit more readable and flexible.

Could you remove `willExpireIn` and add a function `isValidUntil`. That function should take in an instance of `Carbon`.

**Comment by DemianD** [comment]
Hi,

I'm not sure I quite understand.
E.g. we have a certificate that's valid until 17/08/2016 16:50 and we are 11/08/2016.

I want to be sure that the certificate is still 7 days valid. 

```php
$this->certificate->isValidUntil(10/08/2016); // false
$this->certificate->isValidUntil(12/08/2016); // true
```

That carbon instance of the isValidUntil method, is that the new expiration date?
If so, I understand and will send a new pull request.

Demian

**Comment by freekmurze** [comment]
I'd like this code to work:

```php
$this->certificate->isValidUntil(Carbon::create()->addDays(7));
```

This should false if the certificate is valid now at at least until the datetime value of the carbon object given.

You'll find more info on Carbon [here](http://carbon.nesbot.com/docs/).

If you have any more questions, ask away!

**Comment by DemianD** [comment]
Hi Freek,

Just commited the new method.
Also updated the tests. Do you mind the comments next to the tests?

Need to upgrade the readme.md but will wait until it is how you want it

**Comment by freekmurze** [comment]
Hi, changes seem good. 

I have a few nitpicks. I could easily fix them myself after pulling, but maybe it's more useful to you if I explain some of the reasoning to you. Your code is certainly ok, but it could be even better.

Here's your improved code with comments:
```php
// that ":" should be against the ")" like in other methods
public function isValidUntil(Carbon $date, string $url = null): bool
{
   // this test should go first as it is the easiest one to reason about. All the used variables are
   // known in this function
   if($this->expirationDate()->gt($date)) {
       return false;
   }

   // if we remove the negation here we can just return the result of the function
   // being able to dump an if statement always makes me feel good :-)
   return $this->isValid($url);
}
```

Could you makes these changes in the code and update the readme?

**Comment by freekmurze** [comment]
Thanks!

**Comment by DemianD** [comment]
Hi, you are right.

Tomorrow, I will install PHP CodeSniffer and doing some research in coding standards. I want to program more consistent.

Thanks for the feedback. Will keep it in mind !

**Pull request merged**
