### PR TITLE
Allow Carbon v3

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like the tests are failing for Carbon v3. Could you have a look?

**Comment by lloricode** [comment]
checking

**Comment by lloricode** [comment]
Hi @freekmurze, done on fixing test, also added matrix for canbon v2 and v3 to make sure all works,

thank you

**Comment by freekmurze** [comment]
Perfect, thanks!

**Comment by PhilETaylor** [comment]
This is a breaking change. 

With   spatie/ssl-certificate v2.6.4 (which installs Carbon 2.72.3)  `$certificate->expirationDate()->diffInDays()` returns a POSITIVE integer E.g `2.34534` days to go until expiration

With   spatie/ssl-certificate v2.6.5 (which installs Carbon  dev-master b4272c2)  `$certificate->expirationDate()->diffInDays()` returns a NEGATIVE integer E.g `-2.34534` days to go until expiration

Which, within a real world app, is interpreted as the SSL being expired and has caused me to email 1000s of users - doh...

**Comment by PhilETaylor** [comment]
This is a breaking change. 

With   spatie/ssl-certificate v2.6.4 (which installs Carbon 2.72.3)  `$certificate->expirationDate()->diffInDays()` returns a POSITIVE integer E.g `75` ✅

With   spatie/ssl-certificate v2.6.5 (which installs Carbon  3.2.1)  `$certificate->expirationDate()->diffInDays()` returns a NEGATIVE double E.g `-75.307162384132` ❌

With   spatie/ssl-certificate v2.6.5 (with FORCED Carbon 2.72.3)  `$certificate->expirationDate()->diffInDays()` returns a POSITIVE integer E.g `75` ✅

Which, within a real world app, is interpreted as the SSL being expired and has caused me to email 1000s of users - doh... 

Reproducer:

```php
<?php
use Spatie\SslCertificate\SslCertificate;
require 'vendor/autoload.php';
$certificate = SslCertificate::createForHostName(parse_url('https://mySites.guru/', \PHP_URL_HOST));
var_dump($certificate->expirationDate()->diffInDays());
```

**Comment by PhilETaylor** [comment]
related comments https://github.com/briannesbitt/Carbon/issues/2971#issuecomment-2006649547

**Comment by kylekatarnls** [comment]
Sorry to come late here, I don't have the full picture of the use case but would challenge the fix here to be sure it matches the intention.

In the case of a certificate expiration, I think it's good not to hide the fact that it's actually already expired. I think the Carbon v2 behavior was actually dangerous because using `daysUntilExpirationDate()` and getting 2 you might think you still have 2 days before expiration, while it actually can mean it may be expired for 2 days already.

So I would actually do:
```php
return -(int) Carbon::now()->diffInDays($endDate);
```

```
// Assuming now is 2024-05-20 midday
var_dump(
    -(int) Carbon::now()->diffInDays('2024-05-23'), // -2
    -(int) Carbon::now()->diffInDays('2024-05-18'), // 2
);
```

Because of the "Until" my intuition calling it would be to get a positive integer when it's not yet expired, and have something else when expired, depending on the feature need this "something else" might be:
- Negative number of days elapsed since expiration
- Simply return `0`
- Throw an exception such as `throw new \LogicException('Already expired')`
- Return a non-integer value (`null` or `false`)

**Comment by kylekatarnls** [comment]
(I misread the code, so I edited my message above, sorry for the noise)

**Comment by turbo124** [comment]
Just to note on the implementation here casting using (int) will still return a negative integer? Is this expected? I would consider intval(abs($x));

**Comment by PhilETaylor** [comment]
I dont mind progress, but this was and is a backward compatibility change that broke implementations and was released in a minor release, not a major release.

**Comment by kylekatarnls** [comment]
I didn't check when was tagged the previous minor but:

```php
        return (int) Carbon::now()->diffInDays($endDate);
```

using Carbon 3 is equivalent to what was apparently the previous code:
```php
        $interval = Carbon::now()->diff($endDate);

        return (int) $interval->format('%r%a');
```

I.E. negative number when expired, positive before expiration.

**Comment by kylekatarnls** [comment]
`(int) Carbon::now()->diffInDays($endDate)` is absolute by default in Carbon v2 only, so if you have constraint locking Carbon to v2, yes, it might be wrong:

`(int) Carbon::now()->diffInDays($endDate, false)`  would ensure value is negative when expired for both v2 and v3.

**Comment by PhilETaylor** [comment]
For me personally I just accepted the change and modified my code for future proofing as stated above 3 months ago. Others were also discussing this change in other places at the same time https://github.com/briannesbitt/Carbon/issues/2971#issuecomment-2006299161 -

**Comment by kylekatarnls** [comment]
BTW, `lifespanInDays` would suffer the same inconsistency. But having a certificate not yet valid is a bit more of an edge-case.

**Pull request merged**
