### PR TITLE
feat: get port from URL

### PR DESCRIPTION
**Pull request by jodovaljow**
Get port from URL

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! Could you add a test for this?

**Comment by jodovaljow** [comment]
> Thanks! Could you add a test for this?

for sure

**Comment by jodovaljow** [comment]
> Thanks! Could you add a test for this?

But to get better I would need a domain that responds using a port other than 443

**Comment by freekmurze** [comment]
Thanks for that test. Could you also mention the new functionality in the readme?

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
